version: '3'
services:
  gateway:
    image: docker.pkg.github.com/it108/achieve-gateway-go/achieve-gateway-go:${GITHUB_SHA}
    container_name: achieve_gateway
    restart: always
    networks:
      - achieve

  networks:
    achieve:
      external:
        name: achieve_network_prod